version: "3"
services:
  suggestions:
      image: 'suggestion-image'
      build:
        context: .
        network: host
        dockerfile: ./Dockerfile
      ports:
        - "8001:8001"
      expose:
        - '8001'
      container_name: ai-suggestions
      volumes:
        - '.:/var/www/html/ai_content'
    proxy:
      build: ./proxy
      container_name: proxy
      ports:
          - "8000:8000"